name: Publish all packages to NPM

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      CODEX_BOT_NOTIFY_EDITORJS_PUBLIC_CHAT:
        required: true

env:
  NOTIFY_WEBHOOK_LINK: ${{ secrets.CODEX_BOT_NOTIFY_EDITORJS_PUBLIC_CHAT }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 22.1.0
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn install

      - name: Create .yarnrc.yml and publish packages
        run: |
          echo "npmAuthToken: ${{ secrets.NPM_TOKEN }}" >> .yarnrc.yml
          yarn publish:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # NOTIFY_WEBHOOK: ${{ secrets.CODEX_BOT_NOTIFY_EDITORJS_PUBLIC_CHAT }}
          NOTIFY_WEBHOOK: https://notify.bot.codex.so/u/U8S04KRK5R51
