name: Publish Packages

on:
  push:
    branches:
      - 'main'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - run: npm run build

      - run: pnpm run publish:ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
