name: Publish Packages

on:
  push:
    branches:
      - 'main'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - run: npm run build

      - run: pnpm run publish:ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true

  notify:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1
      - name: Send a message
        uses: codex-team/action-codexbot-notify@v1
        with:
          webhook: ${{ env.NOTIFY_WEBHOOK_LINK }}
          message: '📦 [${{ steps.package.outputs.name }}](${{ steps.package.outputs.npmjs-link }}) ${{ steps.package.outputs.version }} was published'
